# Richt de patch specifiek op de Deployment uit de base
- target:
    version: v1
    kind: Deployment
    name: energytruth-algoritme
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "250m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1.5Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1500m"

---
# Richt de patch specifiek op de CronJob uit de base
- target:
    group: batch
    version: v1
    kind: CronJob
    name: algoritme-refresher
  patch: |-
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/cpu
      value: "2"
