server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Onbekende routes worden teruggeleid naar index.html
        try_files $uri $uri/ /index.html;
    }
}
