apiVersion: apps/v1
kind: Deployment
metadata:
  name: energytruth-backend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energytruth-backend
  template:
    metadata:
      labels:
        app: energytruth-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/jouw-gebruiker/energytruth-backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
