apiVersion: apps/v1
kind: Deployment
metadata:
  name: energytruth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energytruth-backend
  template:
    metadata:
      labels:
        app: energytruth-backend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: backend
          image: ghcr.io/vikkoutsaftiss/energy-truth-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: ALGORITME_URL
              valueFrom:
                configMapKeyRef:
                  name: network-config
                  key: algoritme_url        
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
