apiVersion: v1
kind: Service
metadata:
  name: energytruth-backend-service
spec:
  selector:
    app: energytruth-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
