apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: energytruth-productie
namePrefix: prod-

resources:
  - ../../base
  - configmap.yaml

configurations:
  - https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/transformerconfigurations/images.yaml

patches:
  - target:
      kind: Deployment
      name: energytruth-backend # Moet exact matchen met de name in base/deployment.yaml
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: energytruth-backend
      spec:
        replicas: 2 # <<< DIT DOET DE UPGRADE NAAR 2 PODS OP PRODUCTIE
