apiVersion: apps/v1
kind: Deployment
metadata:
  name: energytruth-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energytruth-frontend
  template:
    metadata:
      labels:
        app: energytruth-frontend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: frontend
          image: ghcr.io/vikkoutsaftiss/energy-truth-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: network-config
                  key: backend_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
           volumeMounts:
             - name: appsettings-volume
               mountPath: /usr/share/nginx/html/appsettings.json
               subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          configMap:
            name: backend-network-config
            items:
              - key: appsettings.json
                path: appsettings.json         
