apiVersion: v1
kind: Service
metadata:
  name: energytruth-frontend-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: energytruth-frontend  # Moet exact matchen met de labels van de frontend deployment
