apiVersion: apps/v1
kind: Deployment
metadata:
  name: energytruth-frontend
  namespace: energytruth-productie # <<< ZORG DAT DIT OP PRODUCTIE STAAT
spec:
  template:
    spec:
      containers:
        - name: frontend
          ports:
            - containerPort: 80
          env:
            $patch: replace # <<< DIT VOORKOMT DE DUPLICATE VALIDATION ERROR
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: network-config
                  key: backend_url
            - name: ASPNETCORE_URLS
              value: "http://+:80"
