apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: energytruth-ingress
  namespace: energytruth-productie
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mierlofirst.org
      secretName: energytruth-tls-secret
  rules:
    - host: mierlofirst.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-energytruth-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prod-energytruth-backend-service
                port:
                  number: 80
