apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: energytruth-productie
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: energy-truth.nl # Je echte publieke domein
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: energytruth-frontend-service # Kustomize voegt dit voorvoegsel toe
                port:
                  number: 80
  tls:
    - hosts:
        - energy-truth.nl
      secretName: energytruth-tls-secret
