apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-patch.yaml
namespace: energytruth-productie
namePrefix: prod-
replicas:
  - name: energytruth-frontend
    count: 2
