name: Energy-Truth.sln

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen
      uses: actions/checkout@v4

    - name: .NET installeren
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Controleer of je op .NET 8 zit

    - name: Dependencies herstellen
      run: dotnet restore Energy-Truth.slnx

    # Bonus stap: Checken op de beveiligingslekken die je in je screenshot ziet!
    - name: Check voor kwetsbare pakketten
      run: dotnet list package --vulnerable

    - name: Project bouwen
      run: dotnet build Energy-Truth.slnx --no-restore --configuration Release

    - name: Unit Tests draaien
      # Hij vindt automatisch je 'xUnit tests' project binnen de solution
      run: dotnet test Energy-Truth.slnx --no-build --verbosity normal
