name: Energy-Truth.sln

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore Dependencies
      run: dotnet restore Energy-Truth.slnx

    - name: Check for packages with vulnerabilities
      run: dotnet list package --vulnerable

    - name: Build project
      run: dotnet build Energy-Truth.slnx --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test Tests/EnergyTruth.tests.csproj --configuration Debug --verbosity normal
